### ISSUE TITLE
Connecting Line

### ISSUE THREAD

**Issue by ChekTek** [vincaslt/vscode-highlight-matching-tag#104]
So in a similar extension I use for other languages (Bracket Pair Colorizer 2) there is an option to have a line connecting the starting bracket to the ending bracket. I think this would be an awesome feature!

```
"bracket-pair-colorizer-2.scopeLineCSS": [
        "borderStyle : solid",
        "borderWidth : 2px",
        "borderColor : #876183",
        "opacity: 1"
    ],
```

**Comment by vincaslt** [comment]
I agree, it's not immediately clear to me how that would look like in case of tag breaking to the next line. But if you would like to submit a PR for this I'd happily take a look.

**Comment by vincaslt** [comment]
Closing this in favor of #82 they will be fixed together
