### ISSUE TITLE
Self-closing tags are not properly recognized

### ISSUE THREAD

**Issue by Maaartinus** [vincaslt/vscode-highlight-matching-tag#105]
In JSX, the following gets matched incorrectly
```
	return <div>
		<div className={classes.edgeInner}/>
	</div>;
```
When the cursor stands on the closing "div" the self-closed "div" gets highlighted as match.

It can be fixed by adding an (otherwise useless) space before `/>`.

**Comment by vincaslt** [comment]
Will be fixed with next update.
