### ISSUE TITLE
STOP ADVERTISING ALL THE TIME

### ISSUE THREAD

**Issue by joeherold** [vincaslt/vscode-highlight-matching-tag#108]
Please! Stop advertising nonstop within VS Code. This is SUPER ANNOYING!!!

**Comment by joeherold** [comment]
![image](https://user-images.githubusercontent.com/3911545/79017589-05ae0400-7b72-11ea-9b8d-2a0dff4433c1.png)

I dismissed it today over 25 times!

**Comment by BostjanPisler** [comment]
Agreed, saw it first time, clicked it, no need to show spam.

**Comment by joeherold** [comment]
I am super frustrated, that product spam now entered the VS Code Dev world...
Reported abuse to microsoft
👎

**Comment by WardsParadox** [comment]
Let's not duplicate and spam the author, I'd recommend closing and just follow #106

**Comment by joeherold** [comment]
the author spams us... heavily... :-)

**Comment by DannyFeliz** [comment]
Here how to return to the previous version https://github.com/vincaslt/vscode-highlight-matching-tag/issues/106#issuecomment-612190877

**Comment by vincaslt** [comment]
Sorry, it was a genuine mistake that it showed more than once and only once, it was not intended and did not come up when testing. Thanks @Keanu73 for the PR to remove it and an update was published asap.

**Comment by joeherold** [comment]
thanks for removing this behabviour
