### ISSUE TITLE
Remove the Spam

### ISSUE THREAD

**Issue by genericandy** [vincaslt/vscode-highlight-matching-tag#109]
Do not abuse the update notice for spam notices.

**Comment by WardsParadox** [comment]
Let's not duplicate and spam the author, I'd recommend closing and just follow #106

**Comment by genericandy** [comment]
@WardsParadox  - I was just coming to close it after seeing the other thread.

**Comment by WardsParadox** [comment]
All good, sorry if came across rough, was more just hitting them in advance. No one loves crazy amounts of dups :D
