### ISSUE TITLE
Your Advertisement ruined a good plugin...

### ISSUE THREAD

**Issue by Slurpgoose** [vincaslt/vscode-highlight-matching-tag#110]
I have been a user of this plugin for the last 6 months. Now every time I switch files your advertisement comes up to go buy your course... 

I have uninstalled this plugin and will not be using this in the future

with my deepest sincerity,
fuck off

**Comment by HeshamAbdelalem** [comment]
> I have been a user of this plugin for the last 6 months. Now every time I switch files your advertisement comes up to go buy your course...
> 
> I have uninstalled this plugin and will not be using this in the future
> 
> with my deepest sincerity,
> fuck off

+1
please stop this stupid ad which pop up every second!

**Comment by HeshamAbdelalem** [comment]
> I have been a user of this plugin for the last 6 months. Now every time I switch files your advertisement comes up to go buy your course...
> 
> I have uninstalled this plugin and will not be using this in the future
> 
> with my deepest sincerity,
> fuck off

btw downgrading fixed this issue for me 
check it out 
https://github.com/vincaslt/vscode-highlight-matching-tag/issues/106#issuecomment-612190877

**Comment by vincaslt** [comment]
Sorry, it was a genuine mistake that it showed more than once and only once, it was not intended and did not come up when testing. Thanks @Keanu73 for the PR to remove it and an update was published asap.
