### ISSUE TITLE
Remove Power User notification

### ISSUE THREAD

**Issue by Graphandco** [vincaslt/vscode-highlight-matching-tag#112]
Hello, 

I have permanently a notification on VScode :

Highlight Matching Tag is supported by VSCode Power User course. 
 Become a VSCode expert!

How can I disable this notification ?

Thanks in advance !

**Comment by timothymarois** [comment]
If I see this message one more time I'm uninstalling this extension. 

<img width="482" alt="Screenshot 2020-04-11 13 36 06" src="https://user-images.githubusercontent.com/2489333/79050644-79dfba80-7bf9-11ea-9780-344e7eb70a37.png">

**Comment by vincaslt** [comment]
What is your version of the extension? This has been removed already in v0.9.8.
