### ISSUE TITLE
Commnads binding (question)

### ISSUE THREAD

**Issue by greenais** [vincaslt/vscode-highlight-matching-tag#113]
In readme there is just short "Can also be bound" with no details of what "command" prop needed by keybindings.json should look like.
Can you give any example?
It's quite incovenient to call command palette and seacrh for needed command every time...

**Comment by KamasamaK** [comment]
[Keybinding](https://code.visualstudio.com/docs/getstarted/keybindings) is just a feature of VS Code, so I can see why the extension README would not delve into the details, but it does provide a link to the VS Code documentation so I would advise reading that. You can search for commands in the Keyboard Shortcuts UI. If you have some advanced usage that requires editing the `keybindings.json`, the documentation covers that as well. You can copy the command ID from the UI one if you need.

**Comment by greenais** [comment]
Oh, I see - just searched for "Jump" there, wasn't that obvious, sorry. Tnx!
Yes, I need advanced usage as Keyboard Shortcuts doesn't allow me to bind, in example, ctrl+alt+t, no way but manually edit json
