### ISSUE TITLE
Question: Highlight inner text of certain tags  

### ISSUE THREAD

**Issue by Phuket2** [vincaslt/vscode-highlight-matching-tag#117]
I am guessing the answer is no, but _**is it possible with your extension to select the inner text and style it**_?
In looking around your ext seems to come the closest to what I have been able to find at least.  

The reason I am looking for this is that I seem to have a sort of dyslexia when it comes to looking at html. When doing tutorials for tailwind for example, I easily get lost looking around the file trying to find something.  I thought if I could style the inner text with say like a soft glow or something , it may help them stand out.

thanks in advance

**Comment by vincaslt** [comment]
Not possible at this time, but it could be added quite easily

**Comment by vincaslt** [comment]
I added an option `inner`, let me know if it helps. I couldn't find a `textShadow` option that would allow you to make a glowing text though as it's not provided by vscode it seems: https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions
