### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by farhanahzan** [vincaslt/vscode-highlight-matching-tag#119]
- Issue Type: `Bug`
- Extension Name: `highlight-matching-tag`
- Extension Version: `0.10.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by vincaslt** [comment]
Uhm, could you paste?
