### ISSUE TITLE
Some invalid matching

### ISSUE THREAD

**Issue by vincaslt** [vincaslt/vscode-highlight-matching-tag#12]
```
<div style={{ paddingBottom: 40 }}>
</div>
```

Is not matched

**Comment by Vvtu** [comment]
<div onClick={() => {   this.changeStatus() }} >
	click
</div>

Is also not matched.

This is because of '{' , '}' nesting !!!
Fix it, please.

**Comment by vincaslt** [comment]
Yea, there are multiple cases like that, mostly related to JSX syntax. I tried fishing out most common cases, but missed some like this. Since VSCode since recently has some simple matching already built in, I'm not in a hurry to fix this.

**Comment by Vvtu** [comment]
Thank you, for your answer. 
I have found vscode now  supports this functionality by itself.
I switched to it.  
Your extension in some way is even better then vscode’s. But bugs.

Thank you.
Vvtu.

**Comment by adarshmadrecha** [comment]
The plugin working fine
![hilighting1](https://user-images.githubusercontent.com/11911938/33118300-612b6730-cf91-11e7-8516-8fb3194a2975.JPG)

Plugin not working
![hilighting2](https://user-images.githubusercontent.com/11911938/33118298-60dcd61a-cf91-11e7-8ca4-a3cf433d1410.JPG)

**Comment by vincaslt** [comment]
Should be fixed with v0.5, test cases cover it now.
