### ISSUE TITLE
Expected comma error!

### ISSUE THREAD

**Issue by VanshSh** [vincaslt/vscode-highlight-matching-tag#125]
Issue Type: <b>Bug</b>

I thnk due to this error every time i change my CSS/HTML code i have to refresh my browser to see those changes .
plz help

Extension version: 0.10.0
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.39GB free)|
|Process Argv|--crash-reporter-id b35c49ce-6a91-4a83-8438-477cd6a04aea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by hkbertoson** [comment]
What exactly is your issue? I dont see any error messages.

**Comment by vincaslt** [comment]
I don't see an error message, only your PC specs.

Why would you not have to refresh the browser to load file changes? Are you using some file hot-reload or something?

**Comment by hkbertoson** [comment]
> I don't see an error message, only your PC specs.
> 
> Why would you not have to refresh the browser to load file changes? Are you using some file hot-reload or something?

I was wondering that same exact thing.

**Comment by VanshSh** [comment]
Thnks .
Solved the issue .
