### ISSUE TITLE
Silently crashes on latest version of VS Code (1.15.1)

### ISSUE THREAD

**Issue by HelloDeadline** [vincaslt/vscode-highlight-matching-tag#13]
After update to 1.15.1 I noticed that after I change something in some React files, I have no longer Eslint or Prettier or some other extensions work correctly. I tried everything: uninstall and install again VS Code, on and off some extensions - nothing helped. I reduced my extensions list to a very small amount and by disabling one by one and checking the result I found who was the killer. 

IDK if you could reproduce this issue, but here what I've got:

Linux Mint 18.1 Serena
VS Code 1.15.1

Tested in .js document in React component (~160 lines of code in the file including empty lines)

Console was silent. 

Hope you'll fix this issue. For now I have to uninstall it because it totally ruins workflow.

**Comment by HelloDeadline** [comment]
Also in Insiders with highlight-matching-tag installed I experienced huge delay using Tab with Emmet on. It made impossible to use Emmet. 
(Problem mentioned here: https://github.com/Microsoft/vscode/issues/32371#issuecomment-325603000)

**Comment by vincaslt** [comment]
v0.5 should improve the performance.
