### ISSUE TITLE
Selected text not highlighting

### ISSUE THREAD

**Issue by Katia-Kovtun** [vincaslt/vscode-highlight-matching-tag#131]
Hi there!
Thank you for the extension, it helps a lot!
Unfortunately I faced a small bug, I made custom settings for tags, but now when i try to select part of a tag (class name in tag) the background of selected text doesn't change. Do you have some custom setting for the color of selected text?
`"highlight-matching-tag.styles": {
        "opening": {
            "full": {
              "custom": {
                "dark": {
                  "borderWidth": "0 0 1px 0",
                  "borderColor": "white",
                  "borderStyle": "solid",
                  "borderRadius": "4px",
                  "right": "10px",
                  "backgroundColor" : "MidnightBlue"
                },
                "light": {
                  "borderWidth": "0 0 1px 0",
                  "borderColor": "brown",
                  "borderStyle": "solid",
                  "borderRadius": "4px",
                  "right": "10px",
                  "backgroundColor" : "SeaShell"
                }
              }
            }
        },
        "closing": {
            "full": {
              "custom": {
                "dark": {
                  "borderWidth": "0 0 1px 0",
                  "borderColor": "white",
                  "borderStyle": "solid",
                  "borderRadius": "4px",
                  "right": "10px",
                  "backgroundColor" : "MidnightBlue"
                },
                "light": {
                  "borderWidth": "0 0 1px 0",
                  "borderColor": "brown",
                  "borderStyle": "solid",
                  "borderRadius": "4px",
                  "right": "10px",
                  "backgroundColor" : "SeaShell"
                }
              }
            }
        }
      }`
[http://i.prntscr.com/MppZsZGXRp6_fHx2jbmAcg.png](http://i.prntscr.com/MppZsZGXRp6_fHx2jbmAcg.png) 'phone title' is selected

**Comment by vincaslt** [comment]
Seems like decorations applied by the extension are taking priority now for some reason, so editor's selection is not visible...
I'll try to look into it. For the time being, you could use transparent color like: `rgba(0, 0, 128, 0.3)`

**Comment by Katia-Kovtun** [comment]
greate, thank you for the quick response)
this solusion is work for me
