### ISSUE TITLE
Feature Request: Support if-directives from AsciiDoc

### ISSUE THREAD

**Issue by CWempe** [vincaslt/vscode-highlight-matching-tag#132]
It would be great if `ifdef` and `endif` [directives from AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/#ifdef) would be supported.
These "blocks" are not defined by brackets or tags, but I think it would be usefull to hightloight the connection from `ifdef` to "endif`.

The blocks are defined from `ifdef::foo[]` (or `ifndef:foo[]`) to `endif`.

```
ifdef::foo[]
This content is for GitHub only.
endif::[]
```

Or `endif::[]` can include the same attribute as the beginning like `endif::foo[]`. 
```
ifdef::foo[]
Thius is some Text.
And some more Text.
endif::foo[]
```

There is also `ifeval`:
You can use this to supports multiple languages in one document.
And this is where this addon would provide better readability.

```
ifeval::["{lang}" == "de"]
Das ist mein Text.
endif::[]
ifeval::["{lang}" == "en"]
This is my text.
endif::[]
ifeval::["{lang}" == "es"]
Spanish text.
endif::[]
```

There are also one-liner, that I would not highlight.

```
ifdef::foo[This is some text]
```

**Comment by vincaslt** [comment]
This is out of scope
