### ISSUE TITLE
"highlight-matching-tag.showPath": true is not working.

### ISSUE THREAD

**Issue by jano23** [vincaslt/vscode-highlight-matching-tag#136]
:true does not show path in status bar

Enables/disables showing path to tag in status bar (e.g. div > p > a)

Highlight Matching Tag v0.10.1

VSC About:
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by jano23** [comment]
NEVER MIND
It is working now after disabling/enabling and restarting VSCode
Thanks for a very useful extension!!

**Comment by Ian-Boraks** [comment]
I am having the same issue, but disabling/enabling and restarting VSCode did not fix my problem :(
