### ISSUE TITLE
Works very slowly in large files

### ISSUE THREAD

**Issue by yantakus** [vincaslt/vscode-highlight-matching-tag#14]
It works quickly for me in small files. But in a JSX file with 1000+ lines of code, it takes about 2 seconds for it to highlight appropriate tag. Is this considered normal?

**Comment by vincaslt** [comment]
No, and I've noticed this problem, but then again, why is your JSX file over 1000 lines? :D

**Comment by yantakus** [comment]
Some of my teammates are junior developers, not my fault.

Also, I noticed that when working on such big files, extension becomes laggy and slightly freezes the whole app.

**Comment by vincaslt** [comment]
I'm closing this, because there were some major improvements to the extension, and you have not provided any test data to work with. Reopen this if you think it's still a problem.
