### ISSUE TITLE
cant see the yellow line left 

### ISSUE THREAD

**Issue by Mr54233** [vincaslt/vscode-highlight-matching-tag#142]
![image](https://user-images.githubusercontent.com/46802509/185117026-b171afb3-9128-4a43-aa4d-60a17ebc403b.png)
this is your's image 

![image](https://user-images.githubusercontent.com/46802509/185117075-2e21001a-36d1-4947-8009-e918d1b1c242.png)
and this is mine 
as you can see the yellow line left not exsit my image

i allready reinstall , swipe the setting.json file  , and i can even see the yellow line  , dude can you tell me where am i wrong?

**Comment by daydash** [comment]
> ![image](https://user-images.githubusercontent.com/46802509/185117026-b171afb3-9128-4a43-aa4d-60a17ebc403b.png) this is your's image
> 
> ![image](https://user-images.githubusercontent.com/46802509/185117075-2e21001a-36d1-4947-8009-e918d1b1c242.png) and this is mine as you can see the yellow line left not exsit my image
> 
> i allready reinstall , swipe the setting.json file , and i can even see the yellow line , dude can you tell me where am i wrong?

...
I can't even see those multicolors boxes to differentiate indentation.
![highlight_err](https://user-images.githubusercontent.com/85361115/225413336-bc7473cd-780b-4283-baeb-37e88e28d614.JPG)

**Comment by vincaslt** [comment]
That yellow line on the left is not from my extension, probably colored brackets or something like that, it's showing the scope of the brackets surrounding the JSX code, not the matching tags.

**Comment by 0Chan-smc** [comment]
> That yellow line on the left is not from my extension, probably colored brackets or something like that, it's showing the scope of the brackets surrounding the JSX code, not the matching tags.

I'm really looking for it, could you please share the name of that bracket extension?
