### ISSUE TITLE
[Request] add a command: Select tag

### ISSUE THREAD

**Issue by HenryTSZ** [vincaslt/vscode-highlight-matching-tag#144]
Hi and thanks for an awesome extension!

Currently, there is only one select ommand:

> Select contents of matching tag pair

for example:

```html
<div>contents</div>
```

At present, you can only selected `contents` with command `Select contents of matching tag pair`

but I want to selected `<div>contents</div>`

Can you add this command?

**Comment by vincaslt** [comment]
Done! Added in the new version.
