### ISSUE TITLE
Colon in html element attribute breaks highlighting

### ISSUE THREAD

**Issue by romines** [vincaslt/vscode-highlight-matching-tag#17]
![image](https://user-images.githubusercontent.com/1072819/30938237-9bedb476-a396-11e7-835a-ce26ef1c5940.png)

If a colon is used in an html element attribute (required for Vue `v-bind` directives), it breaks highlighting. Perhaps related to #7?

Thank you for an absolutely essential extension!

**Comment by krittanon-w** [comment]
I found this like you @romines

**Comment by vincaslt** [comment]
Should be fixed with v0.5, test cases cover it now.
