### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by anthonyholmes** [vincaslt/vscode-highlight-matching-tag#19]
After a lot of debugging I found my "Code Helper" process was running at 100% CPU usage due to this plugin.

The issue seems to be an input tag with a ref attribute while working in a .vue file

`<input ref="input" />` will cause this to hang while `<input /> is just fine`

**Comment by alexmchardy** [comment]
I also saw high CPU for "Code Helper" and an unresponsive editor when working on JSX files. Disabling `highlight-matching-tag` stopped the bad behavior. This seems to have started happening fairly recently.

**Comment by colinricardo** [comment]
still encountering this issue

**Comment by evenfrost** [comment]
Same for me, large React files become unprocessable with this extension enabled on pretty decent machine.

**Comment by vincaslt** [comment]
Should be fixed in v0.5.
