### ISSUE TITLE
Settings are not working

### ISSUE THREAD

**Issue by vincaslt** [vincaslt/vscode-highlight-matching-tag#2]
Applying custom settings don't seem to be working.

**Comment by druellan** [comment]
+1 Same here

**Comment by vincaslt** [comment]
Hmm, I got them to work actually, but I'll have to look into them further. Can you write down what you're trying to put into settings? I managed to enable/disable the plugin and change the border styles, so it worked for me, however, I needed to close VSCode after applying them.

**Comment by Esteban-Rocha** [comment]
I confirm that settings are only applied when the editor is reloaded.

**Comment by vincaslt** [comment]
Closing this, because setting seem to be working fine when reloading VSCode. Will look into this later on, but for now it doesn't seem to be a problem.

Refer: #3
