### ISSUE TITLE
Cannot read property 'opening' of null

### ISSUE THREAD

**Issue by KamasamaK** [vincaslt/vscode-highlight-matching-tag#24]
The extension is causing a lot of errors with the message "Cannot read property 'opening' of null". The stack trace indicates that it originates at `getClosingTag (${User}\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:61:35)`, which I've found corresponds to [this line](https://github.com/vincaslt/vscode-highlight-matching-tag/blob/16df541d342ec560fa0397687391b6ef67fab5c3/src/extension.ts#L93).

**Comment by vincaslt** [comment]
Should be fixed in v0.5.
