### ISSUE TITLE
Html Tag underline matching

### ISSUE THREAD

**Issue by chabinot** [vincaslt/vscode-highlight-matching-tag#28]
Hello,
How can i have underlined Html Tag like in Sublime Text (BracketHighlighter plugin) ?
Best regards

**Comment by digitalsms** [comment]
Here's what I use to get this style - go to File, Preferences, Settings, and put this in your user settings:

```
  "highlight-matching-tag.style": {
    "textDecoration": "underline"
  },
  "highlight-matching-tag.leftStyle": {
    "borderWidth": "0"
  },
  "highlight-matching-tag.rightStyle": {
    "borderWidth": "0"
  }
```

**Comment by vincaslt** [comment]
I believe the above helped. Otherwise please clarify your question.
