### ISSUE TITLE
Running Save Participants

### ISSUE THREAD

**Issue by walkertrack5** [vincaslt/vscode-highlight-matching-tag#29]
Hi!, 

I have run into a little bug with your package. On save, a new status pops up on the bottom tool bar saying 'Running Save Participants'. I think there is more but I can't make it out. 

It only seems to happen on random files and so far only on large blade.php files. 

Its causing my sftp sync package to not upload. I have uninstalled every single package except sftp and it went away. Once I re installed your package the issue came right back. 

Have you ever run into this or is there a setting to disable whatever is happening? 

Thank you!!
<img width="383" alt="screen shot 2018-03-15 at 3 36 26 pm" src="https://user-images.githubusercontent.com/37078723/37531699-47ca34fc-2913-11e8-9379-2167e0e0f428.png">

**Comment by vincaslt** [comment]
I'm closing this, because there were some major improvements to the extensions, and you have not provided any test data to work with. Reopen this if you think it's still a problem.

This issue does not seem related to whatever this extension is doing.
