### ISSUE TITLE
cannot add "backgroundColor"

### ISSUE THREAD

**Issue by madebyaris** [vincaslt/vscode-highlight-matching-tag#3]
Hi, I can't add BackgroundColor, is it impossible to add background-color css?

here's my code

`    "highlight-matching-tag.leftStyle": {
        "borderWidth": "0 0 0 1px",
        "borderStyle": "dotted",
        "borderColor": "green",
        "borderRadius": "5px",
        "background-color":  "yellow"
    },
    "highlight-matching-tag.rightStyle": {
        "borderWidth": "0 1px 0 0",
        "borderStyle": "dotted",
        "borderColor": "green",
        "borderRadius": "5px",
        "background-color":  "yellow"
    },`

**Comment by vincaslt** [comment]
Yes it is, but you must write the rules in caps lock - `"backgroundColor": "yellow"`

**Comment by madebyaris** [comment]
hi @vincaslt  thank you for your awesome answer,
I already tested it and it worked.
- - - -
I think I misunderstood it, so I want to make <tag> `<tag> </tag>` in yellow color, is it impossible ? or maybe you can suggest me with something closer like this :+1:

**Comment by vincaslt** [comment]
See if maybe this will be what you want: 
```
"highlight-matching-tag.leftStyle": false,
"highlight-matching-tag.rightStyle": false,
"highlight-matching-tag.style": {
    "backgroundColor": "yellow"
}
```

**Comment by madebyaris** [comment]
awesome, that's what I looking for. thank you.
----
here's some example how to do that (incase someone didn't understand how to do it )
https://gist.github.com/madebyaris/ce062af77dc0669bcd45c3a30c76b635

**Comment by LoDef** [comment]
Worth mentioning is that it works with RGBA values as well
```
"highlight-matching-tag.style": {
      "backgroundColor": "rgba(255,255,200,0.3)" 
}
```
