### ISSUE TITLE
<cfif> tags don't get highlighted

### ISSUE THREAD

**Issue by morgrowe** [vincaslt/vscode-highlight-matching-tag#30]
Would it be possible to add support for matching `<cfif>` tags? Example of the issue seen below:

![cfif](https://user-images.githubusercontent.com/4726315/38304553-ce6c31b6-3801-11e8-9056-b43afee90018.gif)

Thanks
Morgan

**Comment by vincaslt** [comment]
Should be fixed with v0.5, test cases cover it now.
