### ISSUE TITLE
not completely working with Vuejs

### ISSUE THREAD

**Issue by mobayen** [vincaslt/vscode-highlight-matching-tag#33]
Hi
Thank you, buddy, this extension makes my life much easier.
I just wanted to report a little bug.
it does not work with tags that have Vuejs directives as attributes (or their parent tags).

![screen-shot-2018-06-05-at-6 17 39-pm](https://user-images.githubusercontent.com/29548601/41007987-1b396d3e-68ee-11e8-87b7-39520213ab4c.jpg)

**Comment by vincaslt** [comment]
Thanks for reporting this. When reporting a bug, it would be nice to also have the sample code in copy-paste'able format.

**Comment by mobayen** [comment]
@vincaslt you right.
here you go:
`<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8" v-bind:id="x">
                <div class="card card-default">
                    <div class="card-header">Example A</div>

                    <div class="card-body">
                        Matching tags do not work
                    </div>
                </div>
            </div>
            <div class="col-md-8" v-if="x">
                <div class="card card-default">
                    <div class="card-header">Example B</div>

                    <div class="card-body">
                        Matching tags working 
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>`

**Comment by mobayen** [comment]
@vincaslt you right.
here you go:

`<template>
    <div>
        <div v-bind:id="x">
            Matching tags do not work
        </div>
        <div v-if="y">
            Matching tags working 
        </div>
    </div>
</template>`

**Comment by mobayen** [comment]
Not all directives but it seem something goes wrong when the colon added
` v-bind:id="x"`

**Comment by vincaslt** [comment]
Should be fixed with v0.5, test cases cover it now.

**Comment by mobayen** [comment]
nope, the issue still there
 I just checked this morning!

**Comment by vincaslt** [comment]
I'll take a look later in the day.

**Comment by vincaslt** [comment]
Would you be able to provide the exact case you're having problems with? I have just checked the above example and it's working for me:

http://g.recordit.co/5SlVyM3Hx5.gif

Maybe you haven't updated the extension?

**Comment by mobayen** [comment]
oh sorry, you were right!!
it was updated but I didn't reload the vsCode
Thanks, Vincas
