### ISSUE TITLE
The whole tag with attribute value(s) is highlighted!

### ISSUE THREAD

**Issue by abhijeetdeb** [vincaslt/vscode-highlight-matching-tag#37]
This plugin makes the whole tag with attribute value(s) highlighted! This prevents in seeing the block of text I'm trying to copy/cut as the background color remains same. I'm using the following values - 

"highlight-matching-tag.leftStyle": false,
"highlight-matching-tag.rightStyle": false,
"highlight-matching-tag.style": {
    "borderRadius": "2px",
    "backgroundColor": "#34495e",
},

**Comment by vincaslt** [comment]
It indeed does that. What do you think should be the correct behavior?
I was focusing mainly on highlighting on the corners, not the whole block, so it definitely needs to be improved.

**Comment by abhijeetdeb** [comment]
It should only highlight the main tag and not the attributes at all.

E.g. in <div id="one" class="two">Some text</div>, only the 'div' word should be highlighted. We can easily copy/paste/edit the attributes of the tag.

If you can implement that, it'd be great!

**Comment by andrewspy** [comment]
Just to share, I am using border to highlight the matching tag as follow:-

```
    "highlight-matching-tag.leftStyle": {
        "borderWidth": "0 0 0 2px",
        "borderStyle": "solid",
        "borderColor": "#ffc600",
    },
    "highlight-matching-tag.rightStyle": {
        "borderWidth": "0 2px 0 0",
        "borderStyle": "solid",
        "borderColor": "#ffc600",
    },
    "highlight-matching-tag.style": {
        "border": "1px dashed #ffc600",
    },
```

**Comment by abhijeetdeb** [comment]
> I will soon be adding some different default styling options, and more customisation, so hopefully that'll improve the situation. The default now currently is pretty ugly.

Your current extension is still way better than VS Code default. It should have been baked inside the editor! Looking forward to an update. Cheers.

**Comment by abhijeetdeb** [comment]
> Just to share, I am using border to highlight the matching tag as follow:-
> 
> ```
>     "highlight-matching-tag.leftStyle": {
>         "borderWidth": "0 0 0 2px",
>         "borderStyle": "solid",
>         "borderColor": "#ffc600",
>     },
>     "highlight-matching-tag.rightStyle": {
>         "borderWidth": "0 2px 0 0",
>         "borderStyle": "solid",
>         "borderColor": "#ffc600",
>     },
>     "highlight-matching-tag.style": {
>         "border": "1px dashed #ffc600",
>     },
> ```

Hey, I like this. It resolves my attribute copy issue though I'd rather have background highlight than border highlight. I'll be using your "highlight-matching-tag.style" values from now on till @vincaslt comes up with an update. Thanks.

**Comment by vincaslt** [comment]
I've added new styling options, so now you can have separate highlighting settings for name only. Also, when using background color as highlighting it will fall back to underline highlighting when selecting the tag, so that it doesn't interfere, but still provide highlighting. Hope that solves it.
