### ISSUE TITLE
"arrow functions" in jsx confuse the tag matcher

### ISSUE THREAD

**Issue by radix** [vincaslt/vscode-highlight-matching-tag#5]
For example:

```jsx
<div onClick={() => foo()}>
</div>
```

The tag matcher thinks the tag ends at the `>` in `() =>`. usually this doesn't matter much, but it can when you have a self-closing tag:

```jsx
<div>
<div onClick={() => foo()} />
</div>
```

Because of that inner `div`'s arrow function, the extension thinks that the inner div is a regular tag instead of a self-closing tag, and thus shows the bottom `</div>` as the matched tag.

I suppose the easiest solution would be to count `{}`s, `()`s, and probably `""`s inside of tag attributes and only honor a `>` as tag syntax if all other brackets are balanced.

**Comment by vincaslt** [comment]
Yeah, this is in the known issues section already. I haven't had the time to polish the edges. I suppose most of the code for this extension should be rewritten, as it was created to quickly satisfy my need for tag matching. It'd be best to actually write/find a lib that could work with tag matching properly, and not hunting bugs like that one by one from my perpective :)
