### ISSUE TITLE
[Request] Jump between tags

### ISSUE THREAD

**Issue by duranivan** [vincaslt/vscode-highlight-matching-tag#52]
Hi and thanks for an awesome extension!

One thing I am missing from Sublime's BracketHighlighter is that I can jump from one tag to another with one keyboard shortcut, and also select the content in between tags. VS Code's Bracket Pair Colorizer extension does this but for brackets only,

Could it be possible to implement this feature in your extension as well?

Thanks in advance!

**Comment by vincaslt** [comment]
There's now a command to jump to matching tag @KamasamaK did that you can bind on a keyboard shortcut, let me know if that helps.

**Comment by duranivan** [comment]
Sorry to overlook that. Yes, jumping to matching tag works perfectly. Thanks for that.

Any idea if possible to select the content in between tags?

**Comment by vincaslt** [comment]
It's been added just today, no problem ;)

**Comment by vincaslt** [comment]
I've added the command to select content between matching tags in v0.8.4, readme includes instructions on how to setup keybindings for the command.
