### ISSUE TITLE
[Request] Select contents AND tag of matching tag pair

### ISSUE THREAD

**Issue by duranivan** [vincaslt/vscode-highlight-matching-tag#63]
Hi, and thanks a lot for including my previous two requests so speedily.

Probably this will be my last one. I just saw recently the need of selecting not only the contents of matching tag pair but also the content+tag (basically the whole thing between matching pairs including the tag). Could it be possible to have a command for this as well? So to have two commands, the current for content only, and one for content+tag.

Thanks in advance!

**Comment by KamasamaK** [comment]
What language are you looking to use this for? This might already be supported with the `Emmet: Balance (outward)` command. If not, there is going to be a new API introduced for Microsoft/vscode#4795 that would be preferable to the way the selection commands here would be implemented.

**Comment by duranivan** [comment]
I'm using it for React (JSX), Vue and basic html. But you are absolutely right, the Emmet balance outward and inward does this already, couldn't have guessed it myself to be honest as the names of the command are kind of weird. Thanks a lot 👍.
