### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by uryu-myao** [vincaslt/vscode-highlight-matching-tag#66]
- Issue Type: `Bug`
- Extension Name: `highlight-matching-tag`
- Extension Version: `0.8.6`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.31.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by vincaslt** [comment]
Please, either provide relevant info or this is going to be closed.
