### ISSUE TITLE
SelfClose tag issue with /> and >

### ISSUE THREAD

**Issue by vanasis** [vincaslt/vscode-highlight-matching-tag#67]
Cant detect a tag like this **>** :: 
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">`
only works with a tag with **/>** :
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>`

**Comment by vincaslt** [comment]
Thanks for the report. Yeah, the algorithm would consider those as unclosed tags, so it would ignore them as invalid.

I will make it so [https://developer.mozilla.org/en-US/docs/Glossary/Empty_element](empty elements) are considered closed even when they are not, and marked if self-closing tag matching flag is set.

**Comment by vincaslt** [comment]
Should be fixed after the version update.

**Comment by KamasamaK** [comment]
It would be nice if the set of empty elements was configurable instead of being hard-coded.

**Comment by vincaslt** [comment]
At the moment I've added only the tags that are defined in html spec. I can imagine few use cases where making it configurable is useful. I suppose it doesn't actually hurt to make them configurable, but I am not sure parser at the moment would be able to handle tags that could be both empty and not, and I don't want to complicate that part too much.

Maybe that could be an improvement, but currently I don't really see a reason to add that.

**Comment by KamasamaK** [comment]
I think handling tags that could be either empty or not is a complication that would be largely unaffected by the request for configurability -- just make it clear in the configuration description that adding something like that would make it interpreted as always empty. There is no drawback to not having it hard-coded, and the benefit is customization. Even if you want to strictly limit the extension's use to HTML, it's possible that future iterations of the spec introduce new elements when the extension is abandoned. Even now, custom elements are part of the HTML spec via Web Components. But of course, why make it restricted to HTML? You can make clear that the defaults and official support are for some current HTML spec while allowing reasonable configurability.

**Comment by vincaslt** [comment]
Makes sense. Gonna leave this as an open improvement (#69) for some later version, since the immediate problem is fixed.
