### ISSUE TITLE
Tags with dots in them break the parser

### ISSUE THREAD

**Issue by radix** [vincaslt/vscode-highlight-matching-tag#7]
Hey @vincaslt ! I'm super stoked that you worked on a fix for #5 , but sadly I have to report that it seems to have introduced a different issue with JSX: now tags that have dots in them are breaking the parser. This happens when code imports a module and uses a qualified name to specify the tag:

```typescript
import * as CV from './CommonView';

function foo() {
    return <CV.Whatever><span>Hi!</span></CV.Whatever>;
}
```

This is also breaking when any child has a tag that is prefixed by the parent tag, then followed by a dotted name after. I realize that's a confusing formulation, here's an example:

```typescript
function foo() {
    return <X><X.Whatever /></X>;
}
```

In this example the `<X>` doesn't match with the `</X>`. I'm noticing this when using certain libraries like react.semantic-ui.com, which nests component classes, so you use stuff like:

```typescript
function foo() {
    return <Form><Form.Button>Submit</Form.Button></Form>;
}
```

It *think* that neither of these behaviors happened before the latest release (i.e. the tags would match properly as long as there was no `=>` confusing it), but I'm not 100% certain.

If you're not interested in supporting JSX I understand, I just thought I'd let you know!

**Comment by vincaslt** [comment]
Hmm, I didn't expect dots to be in the name, but that makes sense.

**Comment by vincaslt** [comment]
Thanks for reporting your findings! I think it should be working properly now.
