### ISSUE TITLE
Editable Ruler Color

### ISSUE THREAD

**Issue by vanasis** [vincaslt/vscode-highlight-matching-tag#70]
As a title said request a editable rulerColor
currently it is always yellow

https://github.com/vincaslt/vscode-highlight-matching-tag/blob/af2e298cb755074a7daf26b016a173b14c616443/src/tagStyler.ts#L93

```
let options: vscode.DecorationRenderOptions = config.showRuler
      ? {
          overviewRulerLane: vscode.OverviewRulerLane.Center,
          overviewRulerColor:
            decorationConfig.highlight ||
            decorationConfig.surround ||
            decorationConfig.underline ||
            'yellow'
        }
      : {}
```

**Comment by vincaslt** [comment]
Would you like it to be different from the color used to underline the text?
Right now it's supposed to be the same color that's used for highlighting/underlining.

**Comment by vanasis** [comment]
![Screenshot (483)](https://user-images.githubusercontent.com/2195153/55503235-84b95400-5663-11e9-8366-e79e141eda42.png)
I mean yellow color from right side
maybe I do something wrong with settings
but anyway this is my setting for color


```
    "editor.occurrencesHighlight": false,
    "highlight-matching-tag.styles": {
        "opening": {
            "name": {
                "custom": {
                    "dark": {
                        "backgroundColor": "#ADD6FF26",
                    },
                    "light": {
                        "backgroundColor": "#ADD6FF80",
                    }
                }
            }
        }
    },
    "highlight-matching-tag.highlightSelfClosing": true,
```

**Comment by vincaslt** [comment]
Huh, I haven't thought about how they would behave with custom decorations, maybe it makes sense to make them customizable separately for cases like that. I'll add that tomorrow.

**Comment by vincaslt** [comment]
Funny, apparently there was a way to change the color without making any changes after all 😄 

custom `overviewRulerColor` rule will do what you want:

```
"custom": {
    "dark": {
        "backgroundColor": "#ADD6FF26",
        "overviewRulerColor": "red"
    },
    "light": {
        "backgroundColor": "#ADD6FF80",
        "overviewRulerColor": "red"
    }
}
```

**Comment by vanasis** [comment]
```
    "editor.occurrencesHighlight": false,
    "highlight-matching-tag.styles": {
        "opening": {
            "name": {
                "custom": {
                    "dark": {
                        "backgroundColor": "#ADD6FF26",
                        "overviewRulerColor": "silver",
                    },
                    "light": {
                        "backgroundColor": "#ADD6FF80",
                        "overviewRulerColor": "silver",
                    }
                }
            }
        }
    },
    "highlight-matching-tag.highlightSelfClosing": true,
```

yes it works, Thanks

the above code is my setting for vscode ( it look like default vscode occurrencesHighlight )

**Comment by SHxKM** [comment]
This doesn't seem to work anymore in the latest VSCode. Also, `showRuler: false` seems to have no effect (`"highlight-matching-tag.showRuler": false`). Any tips?
