### ISSUE TITLE
defaultEmptyElements issue

### ISSUE THREAD

**Issue by vanasis** [vincaslt/vscode-highlight-matching-tag#72]
defaultEmptyElements works only when they are lowercase, but html is not a case sensitive Language
examples:
`<Input Type="Submit" Value="Apply Filter">` ### **not work**
`<input Type="Submit" Value="Apply Filter">` ### **work**

**Comment by vincaslt** [comment]
Well, in the scope of JSX for instance, it is not the same element, not sure how this can be solved optimally.

**Comment by vincaslt** [comment]
Well, this seems a little out of scope for what I would be willing to do. JSX is case sensitive, Html is not. The extension also implicitly supports any kind of markup-based language, which means that it's not that simple to make a generic option to make it case-sensitive or not. It would probably have to be based off of file extensions, or something. I'm not sure about how necessary it is to support this at the moment anyway, so I will not be fixing it at the moment. I would take a look at a PR if anyone wants to try and propose a solution for this..
