### ISSUE TITLE
Clicking outside the tag matches?

### ISSUE THREAD

**Issue by yasinatesim** [vincaslt/vscode-highlight-matching-tag#73]
Hello,

![vscode-1](https://user-images.githubusercontent.com/32565521/56468081-ef260e80-642f-11e9-9c63-d9eab29e1f77.gif)
Clicking inside the tag matches, working.
but,
![vscode-2](https://user-images.githubusercontent.com/32565521/56468089-11b82780-6430-11e9-9cb9-b21c457ba296.gif)
Clicking outside the tag matches, not working.

Can you help me!

Best,
Yasin.

**Comment by vincaslt** [comment]
It is intentionally like this. The cursor is not in the scope `<li>` tag.

**Comment by yasinatesim** [comment]
Ok. Thanks.

Atom editor and Jetbrains IDE's(Webstorm or Phpstorm) in usage as above. But, I think it can be added as an option.

**Comment by KamasamaK** [comment]
Can you define how you expect it to work outside the tag? Given the example below, where `|` represents the cursor, which tag would you expect to be highlighted?

`<ul>|<li>foo</li></ul>`

**Comment by yasinatesim** [comment]
Hi @KamasamaK,

I expect the ```</li>``` highlighted for your example

Another example,

> **Webstorm IDE**

I clicked the ```<ul>``` element **starting point**, match the  ```</ul>``` element
![Sep-02-2019 11-48-21](https://user-images.githubusercontent.com/32565521/64101982-a97f3800-cd77-11e9-8d55-252315ff73b3.gif)
Some way, I clicked the ```<li>``` element  starting point, match the ```</li>``` element.

Thanks.

**Comment by yasinatesim** [comment]
Why was it closed, is it not possible to offer it as an option? @vincaslt

**Comment by vincaslt** [comment]
Feel free to open a PR if you like.

**Comment by yasinatesim** [comment]
Keep it closed for now. I will turn on PR after completing my development.
Thanks 💕😄
