### ISSUE TITLE
how to customise?

### ISSUE THREAD

**Issue by starchild** [vincaslt/vscode-highlight-matching-tag#75]
Hi,

this plugin is really really good, but I want to make the visuals more obvious, but I can't work out how to customise the css.  

I can see the classes etc in your docs, but how to access them?  Sorry, but of a noob question I'm sure.

Thank you.

**Comment by vincaslt** [comment]
You should take a look here: https://code.visualstudio.com/docs/getstarted/settings

It's not CSS classes, but configuration options you need to change. You can start by opening your User Settings JSON and copying one of the examples there. Then you can play around with the values from the documentation on the extension page to find what suits you.

**Comment by vincaslt** [comment]
I hope you found your answer. I will close the issue now, but if you need help, please open a new one with the exact result that you would like to achieve and I will help you write the config that you need.
