### ISSUE TITLE
Highlighting only on tag

### ISSUE THREAD

**Issue by kanlukasz** [vincaslt/vscode-highlight-matching-tag#79]
Hi.
It is possible to highlighting only on tag?

Right now if i put cursor anywhere in tag content - tag is highlighting
Example:
![obraz](https://user-images.githubusercontent.com/30685349/57434478-6256bf80-723b-11e9-9f12-be62505a364a.png)

I would like to highlight **only** while i select tag (putting cursor on it). It is possible?

**Comment by vincaslt** [comment]
Do you mean the tag name part of the tag? I will think about how best to add customization to this. We already have config setting `highlightFromContent`, and there's an implicit default to highlight from name and attributes, maybe it would make sense to make that explicit ant configurable, like:

```
highlightFrom: ['name', 'attributes', 'content']
```

Where you'd be able to pick and choose from where you want to highlight. I'll do something about that this week.

**Comment by kanlukasz** [comment]
Thanks for quick reply.
Yes. I think the tag should only be highlighted when we place the cursor on the tag name

Right now you have something like this:
![obraz](https://user-images.githubusercontent.com/30685349/57436379-d6936200-723f-11e9-90d0-f4b6bbd98061.png)

### In my opinion it should be like this:

_Cursor on tag name - highlight should be **ON**:_
![obraz](https://user-images.githubusercontent.com/30685349/57436471-08a4c400-7240-11e9-9914-e3637500cdcc.png)

_Cursor elsewhere - highlight should be **OFF**:_
![obraz](https://user-images.githubusercontent.com/30685349/57436549-3558db80-7240-11e9-8738-582f7101715a.png)

**Comment by kanlukasz** [comment]
> Where you'd be able to pick and choose from where you want to highlight. I'll do something about that this week.

I'm sorry to bother you, but I just want to ask about some news about this future? Have you found a moment to implement?

I know it's a free open source project and everyone has a job and life. I just only ask so don't be angry :-)

**Comment by vincaslt** [comment]
Yeah, I switched jobs a month ago and had little time and motivation to maintain the extension. I quickly added some flags to allow better customization from where to match. The one you need to set is: `"highlight-matching-tag.highlightFromAttributes": false` it is `true` by default.

To do it the way I described in the comment above would require more time and testing, because settings should be automatically migrated, and I don't want to do that right now.

**Comment by kanlukasz** [comment]
This is it! Thank you very very very very much!
