### ISSUE TITLE
html tag higlight in PHP code

### ISSUE THREAD

**Issue by Highter87** [vincaslt/vscode-highlight-matching-tag#83]
Something went wrong. Previously highlighted in php code, but it does not work ...

![image](https://user-images.githubusercontent.com/17083227/59191556-871abb80-8b88-11e9-8b97-55d193c4b83e.png)

**Comment by Highter87** [comment]
This is a bug.
This don't hightlight:
```
for( $i = 0; $i<2; $i++ ) {
	$OUT .= "
		<div class='item robotoLight' style=''>
			<div class='' style='padding: 0px 12px;'></div>
		</div>
	";
}
```

And This - work ( notice the space before the number 2 ):
```
for( $i = 0; $i< 2; $i++ ) {
	$OUT .= "
		<div class='item robotoLight' style=''>
			<div class='' style='padding: 0px 12px;'></div>
		</div>
	";
}
```

**Comment by vincaslt** [comment]
Interesting catch. Also if I change/remove the `" "` it works.

**Comment by Highter87** [comment]
I have tried both the regular and the insider versions. Removed all extensions - but there is an error

**Comment by vincaslt** [comment]
This particular error should be fixed after the update.
