### ISSUE TITLE
Doesn't work more

### ISSUE THREAD

**Issue by fandrefh** [vincaslt/vscode-highlight-matching-tag#85]
Unfortunately doesn't work more, was so beautiful...

In my Django Templates, before, everything worked perfectly, but now doesn't work.

**Comment by vincaslt** [comment]
Could you provide a code example with which it won't work?

**Comment by amrifaezeh** [comment]
i have the same issue, the vscode mark the type of the document as "django-html" and not the html. is there anyway to associate with "django-html"?

![image](https://user-images.githubusercontent.com/49558522/64401111-e6ae3780-d0a1-11e9-83da-cf2aeab21c6a.png)

something like beautify settings 

![image](https://user-images.githubusercontent.com/49558522/64401124-034a6f80-d0a2-11e9-9729-0b3355076755.png)
