### ISSUE TITLE
Highlight underline seems overridden by VSCODE highlight

### ISSUE THREAD

**Issue by DenaByte** [vincaslt/vscode-highlight-matching-tag#88]
The underline highlight seems to be overridden by the default highlight from VSCODE when the cursor is inside the tag name as shown in the picture

![highlight_issue](https://user-images.githubusercontent.com/26298592/64113130-21f2f280-cd92-11e9-9ad0-c69f68a3912b.png)

**Comment by KamasamaK** [comment]
I am not able to reproduce this. Even though decorations are capable of being overridden by other decorations, in the case of HTML that highlight is being provided by the language's [`DocumentHighlightProvider`](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#highlight-all-occurrences-of-a-symbol-in-a-document) which does not override decorations, though it does dim the underline.

**Comment by vincaslt** [comment]
It could be that there's a bug when `highlightFromContent` is set. I will try that later.

**Comment by vincaslt** [comment]
Tested it, and it works fine. Could you give the custom settings that you're using (if any) and the code example with which it's not working?

**Comment by DenaByte** [comment]
HTML code naturally. The only personalisation i have is atom theme. Nothing else.

**Comment by jesstech** [comment]
Same problem here.  I work around it by turning off the "Editor: Occurrences Highlight" setting while leaving "Editor: Selection Highlight" enabled.  This switches Code's behavior from highlighting matches under the cursor to highlighting matches on a selection.

**Comment by brynshanahan** [comment]
I'm having this problem as well. Turning "Editor: Occurrences Highlight" off fixes the issue, but I would prefer to leave it on if possible.
The problem doesn't occur when my cursor is over an element attribute instead of over the tag name

![image](https://user-images.githubusercontent.com/37826020/69933767-fa8ffb00-1523-11ea-8361-40fe42e4280b.png)
Hovering over tag name

![image](https://user-images.githubusercontent.com/37826020/69933792-0da2cb00-1524-11ea-85ae-6c395d7eaf10.png)
Hovering over attributes

**Comment by Hariama** [comment]
+1 On the problem that is mentioned above, can reproduce this bug. Turning "Editor: Occurrences Highlight" functions as a workaround, but it's really not handy to turn off all highlights of all occurrences of a name in other languages.

**Comment by keidarcy** [comment]
add this to `settings.json`
```
"editor.occurrencesHighlight": false
```

**Comment by DenaByte** [comment]
Seems I've forgotten about this issue being left open.
At this point, the problem isn't present anymore so will close the issue.
