### ISSUE TITLE
Extend with custom tags ?

### ISSUE THREAD

**Issue by laurent-d** [vincaslt/vscode-highlight-matching-tag#89]
Hi @vincaslt ,

Thanks for your amazing job !! 
Do you plan a setting to add custom tag matching ?

All the best

**Comment by vincaslt** [comment]
What do you mean exactly by custom tag matching?

**Comment by guillermoarb** [comment]
Yes, for example in C code, is there a way to use this to match tag like #if #endif  ???

**Comment by vincaslt** [comment]
No
