### ISSUE TITLE
High cpu usage - vscode unstable

### ISSUE THREAD

**Issue by Esteban-Rocha** [vincaslt/vscode-highlight-matching-tag#9]
Latest update makes CPU go crazy, and for whatever reason kills vs-code integrated emmet functionality, I tested and disabled all extensions and debugged one by one so I'm petty sure the issue is on this addon.

**Comment by vincaslt** [comment]
Could you help me by doing/answering at least one or all of the following?

* What file have you opened when you notice the high load? (If you can't upload it here, could you tell what size it is?)
* How many tabs do you have open?
* Your operating system and general specs?

**Comment by vincaslt** [comment]
Please update your extension, and tell me if there should be the same problem now.
I've checked my cpu load now, and I don't see much difference when opening file with 300k+ tags, vs 2. Default emmet plugin seemed to be working fine as well.
