### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cristianfb1989** [vincaslt/vscode-highlight-matching-tag#90]
- Issue Type: `Performance`
- Extension Name: `highlight-matching-tag`
- Extension Version: `0.9.5`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\(name)\vincaslt.highlight-matching-tag-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by vincaslt** [comment]
I would be helpful to get the code which caused the problem, and the cpuprofile file.
