### ISSUE TITLE
Tags in commented code are also highlighted

### ISSUE THREAD

**Issue by helix026** [vincaslt/vscode-highlight-matching-tag#97]
As can be seen the image below, tags in commented code are also highlighted. 
Is this intentional, or is it a bug?

![highlight-bug](https://user-images.githubusercontent.com/42115482/68528366-c0ae4900-0317-11ea-8cb0-de1eb66614f9.png)

**Comment by elBeta** [comment]
Yeah, even I wondered the same thing. Thanks for putting up this issue.
